services:
  # Serviço ADK Original (Sara)
  sara-adk:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PYTHONPATH=/app
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/list-apps"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sara-adk.rule=Host(`${EASYPANEL_DOMAIN:-localhost}`)"
      - "traefik.http.services.sara-adk.loadbalancer.server.port=5000"
      - "description=Sara ADK - Agente Direito Médico"
      - "maintainer=Alex"
      - "version=1.0"
    networks:
      - sara-network

networks:
  sara-network:
    driver: bridge 