services:
  agno-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7543:7543"  # Ambas as portas iguais e bem diferentes
    environment:
      - PORT=7543
      - PYTHONPATH=/app
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-AIzaSyD9tPWukHuZFFbSNjTNfuIbH_PQwa3uEZQ}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7543/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agno-api.rule=Host(`${EASYPANEL_DOMAIN:-localhost}`)"
      - "traefik.http.services.agno-api.loadbalancer.server.port=7543"
      - "description=Agno API - Gemini AI Assistant"
      - "maintainer=Alex"
      - "version=2.0"
    networks:
      - agno-network

networks:
  agno-network:
    driver: bridge 